# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jmakolka.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("files/jmakolka/background_fon.jpg"))
        self.background.setObjectName("background")
        self.back = QtWidgets.QLabel(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(10, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Upheaval Pro")
        font.setPointSize(41)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.input_1 = QtWidgets.QLabel(self.centralwidget)
        self.input_1.setGeometry(QtCore.QRect(139, 622, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Upheaval Pro")
        font.setPointSize(41)
        self.input_1.setFont(font)
        self.input_1.setObjectName("input_1")
        self.input_2 = QtWidgets.QLabel(self.centralwidget)
        self.input_2.setGeometry(QtCore.QRect(477, 620, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Upheaval Pro")
        font.setPointSize(41)
        self.input_2.setFont(font)
        self.input_2.setObjectName("input_2")
        self.input_3 = QtWidgets.QLabel(self.centralwidget)
        self.input_3.setGeometry(QtCore.QRect(818, 620, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Upheaval Pro")
        font.setPointSize(41)
        self.input_3.setFont(font)
        self.input_3.setObjectName("input_3")
        self.nums_1 = QtWidgets.QLabel(self.centralwidget)
        self.nums_1.setGeometry(QtCore.QRect(1204, 160, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Upheaval Pro")
        font.setPointSize(30)
        self.nums_1.setFont(font)
        self.nums_1.setObjectName("nums_1")
        self.nums_2 = QtWidgets.QLabel(self.centralwidget)
        self.nums_2.setGeometry(QtCore.QRect(1210, 320, 70, 31))
        font = QtGui.QFont()
        font.setFamily("Upheaval Pro")
        font.setPointSize(30)
        self.nums_2.setFont(font)
        self.nums_2.setObjectName("nums_2")
        self.nums_3 = QtWidgets.QLabel(self.centralwidget)
        self.nums_3.setGeometry(QtCore.QRect(1210, 482, 70, 31))
        font = QtGui.QFont()
        font.setFamily("Upheaval Pro")
        font.setPointSize(30)
        self.nums_3.setFont(font)
        self.nums_3.setObjectName("nums_3")
        self.image_1 = QtWidgets.QLabel(self.centralwidget)
        self.image_1.setGeometry(QtCore.QRect(30, 107, 313, 461))
        self.image_1.setStyleSheet("border-radius: 32px;\n"
"\n"
"")
        self.image_1.setText("")
        self.image_1.setObjectName("image_1")
        self.image_2 = QtWidgets.QLabel(self.centralwidget)
        self.image_2.setGeometry(QtCore.QRect(368, 107, 313, 461))
        self.image_2.setStyleSheet("border-radius: 32px;\n"
"\n"
"")
        self.image_2.setText("")
        self.image_2.setObjectName("image_2")
        self.image_3 = QtWidgets.QLabel(self.centralwidget)
        self.image_3.setGeometry(QtCore.QRect(709, 106, 313, 461))
        self.image_3.setStyleSheet("border-radius: 32px;\n"
"\n"
"")
        self.image_3.setText("")
        self.image_3.setObjectName("image_3")
        self.image_4 = QtWidgets.QLabel(self.centralwidget)
        self.image_4.setGeometry(QtCore.QRect(1065, 106, 131, 141))
        self.image_4.setStyleSheet("border-radius: 22px;\n"
"")
        self.image_4.setText("")
        self.image_4.setObjectName("image_4")
        self.image_5 = QtWidgets.QLabel(self.centralwidget)
        self.image_5.setGeometry(QtCore.QRect(1065, 265, 131, 141))
        self.image_5.setStyleSheet("border-radius: 22px;\n"
"")
        self.image_5.setText("")
        self.image_5.setObjectName("image_5")
        self.image_6 = QtWidgets.QLabel(self.centralwidget)
        self.image_6.setGeometry(QtCore.QRect(1065, 425, 131, 141))
        self.image_6.setStyleSheet("border-radius: 22px;\n"
"\n"
"")
        self.image_6.setText("")
        self.image_6.setObjectName("image_6")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(0, 0, 191, 101))
        self.btn_back.setStyleSheet("background: rgba(205, 214, 219, 0)")
        self.btn_back.setText("")
        self.btn_back.setObjectName("btn_back")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setGeometry(QtCore.QRect(30, 100, 313, 461))
        self.frame_1.setStyleSheet("border-radius: 32px;")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back.setText(_translate("MainWindow", "назад"))
        self.input_1.setText(_translate("MainWindow", "---"))
        self.input_2.setText(_translate("MainWindow", "---"))
        self.input_3.setText(_translate("MainWindow", "---"))
        self.nums_1.setText(_translate("MainWindow", "434"))
        self.nums_2.setText(_translate("MainWindow", "212"))
        self.nums_3.setText(_translate("MainWindow", "314"))
